const biomarkers = {
  biomarkers: [
    "25-Hydroxy Vitamin D (total)",
    "Albumin",
    "AST/SGOT",
    "ALT/SGPT",
    "Basophils, Absolute",
    "Basophils, Percent",
    "Chloride",
    "Calcium",
    "BUN",
    "Eosinophils, Absolute",
    "Eosinophils, Percent",
    "Creatinine",
    "eGFR",
    "Copper",
    "Glucose (Fasting)",
    "HbA1c",
    "Globulin",
    "Folate (Folic Acid)",
    "GGT",
    "Ferritin",
    "LDL Cholestrol",
    "Iron (Serum)",
    "Hematocrit (HCT)",
    "HGB",
    "HDL Cholesterol",
    "Lymphocytes, Percent",
    "Lymphocytes, Absolute",
    "MCV",
    "Neutrophils, Percent",
    "Neutrophils, Absolute",
    "MCHC",
    "MPV",
    "Monocytes, Percent",
    "Monocytes, Absolute",
    "MCH",
    "Total Bilirubin",
    "Total Cholesterol",
    "PLT",
    "Sodium",
    "RBC",
    "Potassium",
    "TIBC",
    "RDW",
    "Phosphorus",
    "Total Protein",
    "UREA",
    "WBC",
    "Zinc Serum",
    "Transferrin",
    "Uric Acid",
    "Triglycerides",
  ],
};

const systems = {
  systems: {
    defenceSystem: [
      "AST/SGOT",
      "ALT/SGPT",
      "Basophils, Absolute",
      "Basophils, Percent",
      "Copper",
      "Eosinophils, Absolute",
      "Eosinophils, Percent",
      "Hematocrit (HCT)",
      "Lymphocytes, Percent",
      "Lymphocytes, Absolute",
      "MCV",
      "Monocytes, Percent",
      "Monocytes, Absolute",
      "Neutrophils, Percent",
      "Neutrophils, Absolute",
      "PLT",
      "WBC",
      "Zinc Serum",
    ],
    digestiveSystem: [
      "Basophils, Percent",
      "BUN",
      "Chloride",
      "Calcium",
      "Eosinophils, Percent",
      "Folate (Folic Acid)",
      "GGT",
      "Globulin",
      "Hematocrit (HCT)",
      "HGB",
      "MCV",
      "Phosphorus",
      "Iron (Serum)",
      "Total Protein",
      "Uric Acid",
      "WBC",
    ],
    detoxSystem: [
      "Albumin",
      "ALT/SGPT",
      "AST/SGOT",
      "BUN",
      "Creatinine",
      "eGFR",
      "Ferritin",
      "GGT",
      "Globulin",
      "HDL Cholesterol",
      "Iron (Serum)",
      "LDL Cholestrol",
      "MCV",
      "RDW",
      "Total Bilirubin",
      "Total Cholesterol",
      "Total Protein",
      "Triglycerides",
    ],
    resilienceSystem: ["Albumin", "Glucose (Fasting)", "HbA1c", "WBC"],
    structuralSystem: [
      "25-Hydroxy Vitamin D (total)",
      "Calcium",
      "Creatinine",
      "Uric Acid",
    ],
    cardiovascularSystem: [
      "25-Hydroxy Vitamin D (total)",
      "Ferritin",
      "Florate (Folic Acid)",
      "Glucose (Fasting)",
      "HbA1c",
      "HDL Cholesterol",
      "LDL Cholestrol",
      "MPV",
      "Triglycerides",
    ],
    energySystem: [
      "BUN",
      "Calcium",
      "Chloride",
      "Ferritin",
      "Glucose (Fasting)",
      "MCH",
      "MCHC",
      "Potassium",
      "RBC",
      "Iron (Serum)",
      "Sodium",
      "TIBC",
      "Total Cholesterol",
      "Triglycerides",
      "Transferrin",
      "UREA",
    ],
  },
};
